# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_game_controller_team.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ssl_game_event_2019_pb2 as ssl__game__event__2019__pb2
import ssl_game_controller_common_pb2 as ssl__game__controller__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ssl_game_controller_team.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1essl_game_controller_team.proto\x1a\x19ssl_game_event_2019.proto\x1a ssl_game_controller_common.proto\"D\n\x10TeamRegistration\x12\x11\n\tteam_name\x18\x01 \x02(\t\x12\x1d\n\tsignature\x18\x02 \x01(\x0b\x32\n.Signature\"\xff\x01\n\x10TeamToController\x12\x1d\n\tsignature\x18\x01 \x01(\x0b\x32\n.Signature\x12\x18\n\x0e\x64\x65sired_keeper\x18\x02 \x01(\x05H\x00\x12\x41\n\x12\x61\x64vantage_response\x18\x03 \x01(\x0e\x32#.TeamToController.AdvantageResponseH\x00\x12\x18\n\x0esubstitute_bot\x18\x04 \x01(\x08H\x00\x12\x0e\n\x04ping\x18\x05 \x01(\x08H\x00\">\n\x11\x41\x64vantageResponse\x12\r\n\tUNDECIDED\x10\x00\x12\x08\n\x04STOP\x10\x00\x12\x0c\n\x08\x43ONTINUE\x10\x01\x1a\x02\x10\x01\x42\x05\n\x03msg\"u\n\x10\x43ontrollerToTeam\x12,\n\x10\x63ontroller_reply\x18\x01 \x01(\x0b\x32\x10.ControllerReplyH\x00\x12,\n\x10\x61\x64vantage_choice\x18\x02 \x01(\x0b\x32\x10.AdvantageChoiceH\x00\x42\x05\n\x03msg\"\xcd\x01\n\x0f\x41\x64vantageChoice\x12#\n\x04\x66oul\x18\x01 \x02(\x0e\x32\x15.AdvantageChoice.Foul\x12\x33\n\x10\x62ot_crash_unique\x18\x02 \x01(\x0b\x32\x19.GameEvent.BotCrashUnique\x12/\n\x0e\x62ot_pushed_bot\x18\x03 \x01(\x0b\x32\x17.GameEvent.BotPushedBot\"/\n\x04\x46oul\x12\x0b\n\x07UNKNOWN\x10\x00\x12\r\n\tCOLLISION\x10\x01\x12\x0b\n\x07PUSHING\x10\x02')
  ,
  dependencies=[ssl__game__event__2019__pb2.DESCRIPTOR,ssl__game__controller__common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TEAMTOCONTROLLER_ADVANTAGERESPONSE = _descriptor.EnumDescriptor(
  name='AdvantageResponse',
  full_name='TeamToController.AdvantageResponse',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDECIDED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTINUE', index=2, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=_descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\020\001')),
  serialized_start=352,
  serialized_end=414,
)
_sym_db.RegisterEnumDescriptor(_TEAMTOCONTROLLER_ADVANTAGERESPONSE)

_ADVANTAGECHOICE_FOUL = _descriptor.EnumDescriptor(
  name='Foul',
  full_name='AdvantageChoice.Foul',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLLISION', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUSHING', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=701,
  serialized_end=748,
)
_sym_db.RegisterEnumDescriptor(_ADVANTAGECHOICE_FOUL)


_TEAMREGISTRATION = _descriptor.Descriptor(
  name='TeamRegistration',
  full_name='TeamRegistration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team_name', full_name='TeamRegistration.team_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='TeamRegistration.signature', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=163,
)


_TEAMTOCONTROLLER = _descriptor.Descriptor(
  name='TeamToController',
  full_name='TeamToController',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature', full_name='TeamToController.signature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='desired_keeper', full_name='TeamToController.desired_keeper', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='advantage_response', full_name='TeamToController.advantage_response', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='substitute_bot', full_name='TeamToController.substitute_bot', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ping', full_name='TeamToController.ping', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TEAMTOCONTROLLER_ADVANTAGERESPONSE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='TeamToController.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=166,
  serialized_end=421,
)


_CONTROLLERTOTEAM = _descriptor.Descriptor(
  name='ControllerToTeam',
  full_name='ControllerToTeam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='controller_reply', full_name='ControllerToTeam.controller_reply', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='advantage_choice', full_name='ControllerToTeam.advantage_choice', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='ControllerToTeam.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=423,
  serialized_end=540,
)


_ADVANTAGECHOICE = _descriptor.Descriptor(
  name='AdvantageChoice',
  full_name='AdvantageChoice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='foul', full_name='AdvantageChoice.foul', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bot_crash_unique', full_name='AdvantageChoice.bot_crash_unique', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bot_pushed_bot', full_name='AdvantageChoice.bot_pushed_bot', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ADVANTAGECHOICE_FOUL,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=543,
  serialized_end=748,
)

_TEAMREGISTRATION.fields_by_name['signature'].message_type = ssl__game__controller__common__pb2._SIGNATURE
_TEAMTOCONTROLLER.fields_by_name['signature'].message_type = ssl__game__controller__common__pb2._SIGNATURE
_TEAMTOCONTROLLER.fields_by_name['advantage_response'].enum_type = _TEAMTOCONTROLLER_ADVANTAGERESPONSE
_TEAMTOCONTROLLER_ADVANTAGERESPONSE.containing_type = _TEAMTOCONTROLLER
_TEAMTOCONTROLLER.oneofs_by_name['msg'].fields.append(
  _TEAMTOCONTROLLER.fields_by_name['desired_keeper'])
_TEAMTOCONTROLLER.fields_by_name['desired_keeper'].containing_oneof = _TEAMTOCONTROLLER.oneofs_by_name['msg']
_TEAMTOCONTROLLER.oneofs_by_name['msg'].fields.append(
  _TEAMTOCONTROLLER.fields_by_name['advantage_response'])
_TEAMTOCONTROLLER.fields_by_name['advantage_response'].containing_oneof = _TEAMTOCONTROLLER.oneofs_by_name['msg']
_TEAMTOCONTROLLER.oneofs_by_name['msg'].fields.append(
  _TEAMTOCONTROLLER.fields_by_name['substitute_bot'])
_TEAMTOCONTROLLER.fields_by_name['substitute_bot'].containing_oneof = _TEAMTOCONTROLLER.oneofs_by_name['msg']
_TEAMTOCONTROLLER.oneofs_by_name['msg'].fields.append(
  _TEAMTOCONTROLLER.fields_by_name['ping'])
_TEAMTOCONTROLLER.fields_by_name['ping'].containing_oneof = _TEAMTOCONTROLLER.oneofs_by_name['msg']
_CONTROLLERTOTEAM.fields_by_name['controller_reply'].message_type = ssl__game__controller__common__pb2._CONTROLLERREPLY
_CONTROLLERTOTEAM.fields_by_name['advantage_choice'].message_type = _ADVANTAGECHOICE
_CONTROLLERTOTEAM.oneofs_by_name['msg'].fields.append(
  _CONTROLLERTOTEAM.fields_by_name['controller_reply'])
_CONTROLLERTOTEAM.fields_by_name['controller_reply'].containing_oneof = _CONTROLLERTOTEAM.oneofs_by_name['msg']
_CONTROLLERTOTEAM.oneofs_by_name['msg'].fields.append(
  _CONTROLLERTOTEAM.fields_by_name['advantage_choice'])
_CONTROLLERTOTEAM.fields_by_name['advantage_choice'].containing_oneof = _CONTROLLERTOTEAM.oneofs_by_name['msg']
_ADVANTAGECHOICE.fields_by_name['foul'].enum_type = _ADVANTAGECHOICE_FOUL
_ADVANTAGECHOICE.fields_by_name['bot_crash_unique'].message_type = ssl__game__event__2019__pb2._GAMEEVENT_BOTCRASHUNIQUE
_ADVANTAGECHOICE.fields_by_name['bot_pushed_bot'].message_type = ssl__game__event__2019__pb2._GAMEEVENT_BOTPUSHEDBOT
_ADVANTAGECHOICE_FOUL.containing_type = _ADVANTAGECHOICE
DESCRIPTOR.message_types_by_name['TeamRegistration'] = _TEAMREGISTRATION
DESCRIPTOR.message_types_by_name['TeamToController'] = _TEAMTOCONTROLLER
DESCRIPTOR.message_types_by_name['ControllerToTeam'] = _CONTROLLERTOTEAM
DESCRIPTOR.message_types_by_name['AdvantageChoice'] = _ADVANTAGECHOICE

TeamRegistration = _reflection.GeneratedProtocolMessageType('TeamRegistration', (_message.Message,), dict(
  DESCRIPTOR = _TEAMREGISTRATION,
  __module__ = 'ssl_game_controller_team_pb2'
  # @@protoc_insertion_point(class_scope:TeamRegistration)
  ))
_sym_db.RegisterMessage(TeamRegistration)

TeamToController = _reflection.GeneratedProtocolMessageType('TeamToController', (_message.Message,), dict(
  DESCRIPTOR = _TEAMTOCONTROLLER,
  __module__ = 'ssl_game_controller_team_pb2'
  # @@protoc_insertion_point(class_scope:TeamToController)
  ))
_sym_db.RegisterMessage(TeamToController)

ControllerToTeam = _reflection.GeneratedProtocolMessageType('ControllerToTeam', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLLERTOTEAM,
  __module__ = 'ssl_game_controller_team_pb2'
  # @@protoc_insertion_point(class_scope:ControllerToTeam)
  ))
_sym_db.RegisterMessage(ControllerToTeam)

AdvantageChoice = _reflection.GeneratedProtocolMessageType('AdvantageChoice', (_message.Message,), dict(
  DESCRIPTOR = _ADVANTAGECHOICE,
  __module__ = 'ssl_game_controller_team_pb2'
  # @@protoc_insertion_point(class_scope:AdvantageChoice)
  ))
_sym_db.RegisterMessage(AdvantageChoice)


_TEAMTOCONTROLLER_ADVANTAGERESPONSE.has_options = True
_TEAMTOCONTROLLER_ADVANTAGERESPONSE._options = _descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
